// HidDfuAPI.cs : Declares the DLL functions for C#.
// Generated by E:\Jenkins\workspace\BlueSuite_v2_6_X_RCY\common\hosttools\bluesuite_2_6\prodtest\scripts\extract_tt_api.pl from HidDfu.h;  at 28/03/17 - 17:49:51
// Copyright (c) 2004-2017 Qualcomm Technologies International, Ltd.
// All Rights Reserved.
// Qualcomm Technologies International, Ltd. Confidential and Proprietary.

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace HidDfuAPI
{
    public enum HID_STATUS
    {
        HIDDFU_ERROR_NONE                             =     0,
        HIDDFU_ERROR_SEQUENCE                         =    -1,
        HIDDFU_ERROR_CONNECTION                       =    -2,
        HIDDFU_ERROR_FILE_OPEN_FAILED                 =    -3,
        HIDDFU_ERROR_FILE_WRITE_FAILED                =    -4,
        HIDDFU_ERROR_FILE_INVALID_FORMAT              =    -5,
        HIDDFU_ERROR_FILE_CRC_INCORRECT               =    -6,
        HIDDFU_ERROR_FILE_READ_FAILED                 =    -7,
        HIDDFU_ERROR_UPGRADE_FAILED                   =    -8,
        HIDDFU_ERROR_RESET_FAILED                     =    -9,
        HIDDFU_ERROR_OUT_OF_MEM                       =    -1,
        HIDDFU_ERROR_INVALID_PARAMETER                =    -1,
        HIDDFU_ERROR_DRIVER_INTERFACE_FAILURE         =    -1,
        HIDDFU_ERROR_OPERATION_FAILED_TO_START        =    -1,
        HIDDFU_ERROR_BUSY                             =    -1,
        HIDDFU_ERROR_CLEAR_STATUS_FAILED              =    -1,
        HIDDFU_ERROR_DEVICE_FIRMWARE                  =    -1,
        HIDDFU_ERROR_UNKNOWN                          =    -2,
    }

    public enum HID_PROCESS
    {
        HID_PROCESS_NONE = 0,
        HID_PROCESS_IN_PROGRESSING,
        HID_PROCESS_FAILD,
        HID_PROCESS_SUCCESS,
        HID_PROCESS_REBOOTING,
    }


    public class HidDfu
    {
#if PocketPC || WindowsCE
        const CharSet charset = CharSet.Auto;
        const CallingConvention calling_convention = CallingConvention.Winapi;
#else
        const CharSet charset = CharSet.Ansi;
        const CallingConvention calling_convention = CallingConvention.StdCall;
#endif

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetVersion",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuGetVersion(out ushort major, out ushort minor, out ushort release, out ushort build);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuConnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuConnect(ushort vid, ushort pid, ushort usage, ushort usagePage, out ushort count);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuDisconnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuDisconnect();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuBackup",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuBackup(String fileName, byte resetAfter);
        [DllImport("HidDfu.dll", EntryPoint="hidDfuBackup",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuBackup(byte [] fileName, byte resetAfter);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuUpgrade",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuUpgrade(String fileName, byte resetAfter);
        [DllImport("HidDfu.dll", EntryPoint="hidDfuUpgrade",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuUpgrade(byte [] fileName, byte resetAfter);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuResetDevice",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuResetDevice();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetProgress",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern byte hidDfuGetProgress();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetResult",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuGetResult();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetLastError",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern IntPtr hidDfuGetLastError();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetFailedDevicesCount",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern byte hidDfuGetFailedDevicesCount();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuSendCommand",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuSendCommand(ref byte data, uint length);

        [DllImport("HidDfu.dll", EntryPoint = "hidDfuUpgradeBin",
        CharSet = charset, CallingConvention = calling_convention)]
        public static extern int hidDfuUpgradeBin(String fileName);
        [DllImport("HidDfu.dll", EntryPoint = "hidDfuUpgradeBin",
                CharSet = charset, CallingConvention = calling_convention)]
        public static extern int hidDfuUpgradeBin(byte[] fileName);

    }
}
